// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwDuyLjymAlzO-Jv_lhgqyNPekZGb-MfQ',
    appId: '1:517902911708:web:0b42cdb74791adad8b8c19',
    messagingSenderId: '517902911708',
    projectId: 'amst-flutter-db-731b4',
    authDomain: 'amst-flutter-db-731b4.firebaseapp.com',
    databaseURL: 'https://amst-flutter-db-731b4-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-731b4.appspot.com',
    measurementId: 'G-ZWX8MVMW5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBfvoMYEGx_t9xjcx210lv41Lin4HNguM',
    appId: '1:517902911708:android:1f2a55b4aa566a8b8b8c19',
    messagingSenderId: '517902911708',
    projectId: 'amst-flutter-db-731b4',
    databaseURL: 'https://amst-flutter-db-731b4-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-731b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgVZx26GLxuYOx4qGPAjx5JZSVPwwLQg4',
    appId: '1:517902911708:ios:18686f74a8bc148d8b8c19',
    messagingSenderId: '517902911708',
    projectId: 'amst-flutter-db-731b4',
    databaseURL: 'https://amst-flutter-db-731b4-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-731b4.appspot.com',
    iosClientId: '517902911708-i88tp8hkujvgje10mdbecs1m2b77715t.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFlutterDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgVZx26GLxuYOx4qGPAjx5JZSVPwwLQg4',
    appId: '1:517902911708:ios:24a0f2e9c4a6ed948b8c19',
    messagingSenderId: '517902911708',
    projectId: 'amst-flutter-db-731b4',
    databaseURL: 'https://amst-flutter-db-731b4-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-731b4.appspot.com',
    iosClientId: '517902911708-a8eo5q3u24is679cjbmaud0dcuvfapgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFlutterDb.RunnerTests',
  );
}
